project:
  type: website
  output-dir: _site

website:
  title: "curiosity-notes"
  site-url: "https://feynlee.github.io/curiosity-notes"
  twitter-card: true
  open-graph: true
  google-analytics: G-343667243
  page-navigation: true
  navbar:
    left:
      - text: Posts
        href: index.qmd
      - text: TIL
        href: TIL.qmd
      - text: Books
        href: books/books.qmd
      - text: AI Art
        menu:
          - text: Disco Diffusion
            href: ai_art-dd.ipynb
          - text: Stable Diffusion
            href: ai_art-sd.ipynb
      - text: Projects
        href: projects.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/feynlee
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/curiosity_notes
        aria-label: Twitter
      - icon: rss
        menu:
          - text: Subscribe to Posts
            icon: rss
            href: https://feynlee.github.io/curiosity-notes/index.xml
            aria-label: Posts RSS
          - text: Subscribe to TIL
            icon: rss
            href: https://feynlee.github.io/curiosity-notes/TIL.xml
            aria-label: TIL RSS
          - text: Subscribe to Projects
            icon: rss
            href: https://feynlee.github.io/curiosity-notes/projects.xml
            aria-label: Projects RSS
  sidebar:
    - id: til
      title: TIL
      contents:
        - section: '2022'
          contents:
          - text: Nbdev_ignore
            href: TIL/2022/2022-11-23-aws-private_subnet_setup.ipynb
          - text: Whisper2Subtitles
            href: TIL/2022/2022-11-16-fastai-store_attr_infinite_recursion.ipynb
          - text: DreamBooth
            href: TIL/2022/2022-11-15-fastai-show_training_loop.ipynb
    - id: projects
      title: Projects
      contents:
        - text: Code-Insertion
          href: Projects/2022-11-25-Code_Insertion.md
        - text: Nbdev_ignore
          href: Projects/2022-11-21-Nbdev_ignore.md
        - text: Whisper2Subtitles
          href: Projects/2022-11-09-Whisper2Subtitles.md
        - text: DreamBooth
          href: Projects/2022-10-01-DreamBooth.md
        - text: Learning Blender
          href: Projects/2021-12-15-Learning_Blender.md
    - id: ai_art
      title: AI Art
      contents:
        - section: Disco Diffusion
          href: ai_art-dd.ipynb
          contents:
            - text: Temple
              href: AI_art/disco_diffusion/01-temple.md
            - text: Cherry Blossom
              href: AI_art/disco_diffusion/02-cherry_blossom.md
            - text: Forest
              href: AI_art/disco_diffusion/03-forest.md
            - text: Dusk
              href: AI_art/disco_diffusion/04-dusk.md
            - text: Islands
              href: AI_art/disco_diffusion/05-islands.md
            - text: Peter Pan
              href: AI_art/disco_diffusion/06-peter_pan.md
            - text: Lagoon
              href: AI_art/disco_diffusion/07-lagoon.md
            - text: Roses
              href: AI_art/disco_diffusion/08-roses.md
            - text: Space Station
              href: AI_art/disco_diffusion/09-space_station.md
            - text: Night Fortress
              href: AI_art/disco_diffusion/10-night_fortress.md
            - text: Jellyfish
              href: AI_art/disco_diffusion/11-jellyfish.md
            - text: Single
              href: AI_art/disco_diffusion/12-singles.md
        - section: Stable Diffusion
          href: ai_art-sd.ipynb
          contents:
            - text: Videos
              href: AI_art/stable_diffusion/01-videos.md


# so that R, Python, and Julia code is only executed locally
execute:
  freeze: auto

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    code-line-numbers: "1"
    code-block-bg: true
    code-block-border-left: true
    code-copy: true
    code-fold: false
    highlight-style: pygments
    smooth-scroll: true
    link-external-newwindow: true
    anchor-sections: true
    header-includes: <script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=637e822e04255c001315118d&product=inline-share-buttons&source=platform" async="async"></script>

# metadata-files: [data/books.yml, data/movies.yml]

